<?php
session_start();
include("../classes/user.php");
require("../classes/php-binance-api.php");
if (isset($_SESSION['user_email'])) {
    $user = new User($_SESSION['user_email']);
    if ($user->isConnected()) {
        $apiKey = $user->GetApiKey();
        $secretKey = $user->GetSecretKey();

        $api = new Binance\API($apiKey, $secretKey);


//        $symbolsArray = explode(',', $symbolString);
//        $symbolsArray = ['BTCUSDT','ETHUSDT','BNBUSDT'];
//        $symbolsArray = ['BTCUSDT','ETHUSDT','BNBUSDT','BCCUSDT','NEOUSDT','LTCUSDT','QTUMUSDT','ADAUSDT','XRPUSDT','EOSUSDT','TUSDUSDT','IOTAUSDT','XLMUSDT','ONTUSDT','TRXUSDT','ETCUSDT','ICXUSDT','VENUSDT','NULSUSDT','VETUSDT','PAXUSDT','BCHABCUSDT','BCHSVUSDT','USDCUSDT','LINKUSDT','WAVESUSDT','BTTUSDT','USDSUSDT','ONGUSDT','HOTUSDT','ZILUSDT','ZRXUSDT','FETUSDT','BATUSDT','XMRUSDT','ZECUSDT','IOSTUSDT','CELRUSDT','DASHUSDT','NANOUSDT','OMGUSDT','THETAUSDT','ENJUSDT','MITHUSDT','MATICUSDT','ATOMUSDT','TFUELUSDT','ONEUSDT','FTMUSDT','ALGOUSDT','USDSBUSDT','GTOUSDT','ERDUSDT','DOGEUSDT','DUSKUSDT','ANKRUSDT','WINUSDT','COSUSDT','NPXSUSDT','COCOSUSDT','MTLUSDT','TOMOUSDT','PERLUSDT','DENTUSDT','MFTUSDT','KEYUSDT','STORMUSDT','DOCKUSDT','WANUSDT','FUNUSDT','CVCUSDT','CHZUSDT','BANDUSDT','BUSDUSDT','BEAMUSDT','XTZUSDT','RENUSDT','RVNUSDT','HCUSDT','HBARUSDT','NKNUSDT','STXUSDT','KAVAUSDT','ARPAUSDT','IOTXUSDT','RLCUSDT','MCOUSDT','CTXCUSDT','BCHUSDT','TROYUSDT','VITEUSDT','FTTUSDT','BUSDTRY','USDTTRY','USDTRUB','EURUSDT','OGNUSDT','DREPUSDT','BULLUSDT','BEARUSDT','ETHBULLUSDT','ETHBEARUSDT','TCTUSDT','WRXUSDT','BTSUSDT','LSKUSDT','BNTUSDT','LTOUSDT','EOSBULLUSDT','EOSBEARUSDT','XRPBULLUSDT','XRPBEARUSDT','STRATUSDT','AIONUSDT','MBLUSDT','COTIUSDT','BNBBULLUSDT','BNBBEARUSDT','STPTUSDT','USDTZAR','WTCUSDT','DATAUSDT','XZCUSDT','SOLUSDT','USDTIDRT','CTSIUSDT','HIVEUSDT','CHRUSDT','BTCUPUSDT','BTCDOWNUSDT','GXSUSDT','ARDRUSDT','LENDUSDT','MDTUSDT','STMXUSDT','KNCUSDT','REPUSDT','LRCUSDT','PNTUSDT','USDTUAH','COMPUSDT','USDTBIDR','BKRWUSDT','SCUSDT','ZENUSDT','SNXUSDT','ETHUPUSDT','ETHDOWNUSDT','ADAUPUSDT','ADADOWNUSDT','LINKUPUSDT','LINKDOWNUSDT','VTHOUSDT','DGBUSDT','GBPUSDT','SXPUSDT','MKRUSDT','DAIUSDT','DCRUSDT','STORJUSDT','BNBUPUSDT','BNBDOWNUSDT','XTZUPUSDT','XTZDOWNUSDT','USDTBKRW','MANAUSDT','AUDUSDT','YFIUSDT','BALUSDT','BLZUSDT','IRISUSDT','KMDUSDT','USDTDAI','JSTUSDT','SRMUSDT','ANTUSDT','CRVUSDT','SANDUSDT','OCEANUSDT','NMRUSDT','DOTUSDT','LUNAUSDT','RSRUSDT','PAXGUSDT','WNXMUSDT','TRBUSDT','BZRXUSDT','SUSHIUSDT','YFIIUSDT','KSMUSDT','EGLDUSDT','DIAUSDT','RUNEUSDT','FIOUSDT','UMAUSDT','EOSUPUSDT','EOSDOWNUSDT','TRXUPUSDT','TRXDOWNUSDT','XRPUPUSDT','XRPDOWNUSDT','DOTUPUSDT','DOTDOWNUSDT','USDTNGN','BELUSDT','WINGUSDT','LTCUPUSDT','LTCDOWNUSDT','UNIUSDT','NBSUSDT','OXTUSDT','SUNUSDT','AVAXUSDT','HNTUSDT','FLMUSDT','UNIUPUSDT','UNIDOWNUSDT','ORNUSDT','UTKUSDT','XVSUSDT','ALPHAUSDT','USDTBRL','AAVEUSDT','NEARUSDT','SXPUPUSDT','SXPDOWNUSDT','FILUSDT','FILUPUSDT','FILDOWNUSDT','YFIUPUSDT','YFIDOWNUSDT','INJUSDT','AUDIOUSDT','CTKUSDT','BCHUPUSDT','BCHDOWNUSDT','AKROUSDT','AXSUSDT','HARDUSDT','DNTUSDT','STRAXUSDT','UNFIUSDT','ROSEUSDT','AVAUSDT','XEMUSDT','AAVEUPUSDT','AAVEDOWNUSDT','SKLUSDT','SUSDUSDT','SUSHIUPUSDT','SUSHIDOWNUSDT','XLMUPUSDT','XLMDOWNUSDT','GRTUSDT','JUVUSDT','PSGUSDT','USDTBVND','1INCHUSDT','REEFUSDT','OGUSDT','ATMUSDT','ASRUSDT','CELOUSDT','RIFUSDT','BTCSTUSDT','TRUUSDT','CKBUSDT','TWTUSDT','FIROUSDT','LITUSDT','SFPUSDT','DODOUSDT','CAKEUSDT','ACMUSDT','BADGERUSDT','FISUSDT','OMUSDT','PONDUSDT','DEGOUSDT','ALICEUSDT','LINAUSDT','PERPUSDT','RAMPUSDT','SUPERUSDT','CFXUSDT','EPSUSDT','AUTOUSDT','TKOUSDT','PUNDIXUSDT','TLMUSDT','1INCHUPUSDT','1INCHDOWNUSDT','BTGUSDT','MIRUSDT','BARUSDT','FORTHUSDT','BAKEUSDT','BURGERUSDT','SLPUSDT','SHIBUSDT','ICPUSDT','USDTGYEN','ARUSDT','POLSUSDT','MDXUSDT','MASKUSDT','LPTUSDT','NUUSDT','XVGUSDT','ATAUSDT','GTCUSDT','TORNUSDT','KEEPUSDT','ERNUSDT','KLAYUSDT','PHAUSDT'];
          $symbolsArray = ['ETCUSDT','BTCUSDT','ETHUSDT'];
        $orderHistory = array();
        foreach ($symbolsArray as $symbol) {
            $orderHistory[$symbol] = $api->openOrders("$symbol");
        }

        echo json_encode(array("orderList" => $orderHistory));

    } else {
        echo json_encode(array("status" => "failed", "msg" => "user is not connected", "user_email" => $user->user_email));
    }
} else {
    echo json_encode(array("status" => "failed", "msg" => "no session"));
}


